// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calcSimpDepth
double calcSimpDepth(NumericVector res, int K);
RcppExport SEXP _GSignTest_calcSimpDepth(SEXP resSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(calcSimpDepth(res, K));
    return rcpp_result_gen;
END_RCPP
}
// signC
int signC(double x);
RcppExport SEXP _GSignTest_signC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(signC(x));
    return rcpp_result_gen;
END_RCPP
}
// calc
int calc(NumericVector x, int k, int ind, int signOld);
RcppExport SEXP _GSignTest_calc(SEXP xSEXP, SEXP kSEXP, SEXP indSEXP, SEXP signOldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type ind(indSEXP);
    Rcpp::traits::input_parameter< int >::type signOld(signOldSEXP);
    rcpp_result_gen = Rcpp::wrap(calc(x, k, ind, signOld));
    return rcpp_result_gen;
END_RCPP
}
// calcDepth_def
double calcDepth_def(NumericVector res, int k);
RcppExport SEXP _GSignTest_calcDepth_def(SEXP resSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDepth_def(res, k));
    return rcpp_result_gen;
END_RCPP
}
// RcppCalcKDepthBlock
double RcppCalcKDepthBlock(NumericVector resSigns, int K);
RcppExport SEXP _GSignTest_RcppCalcKDepthBlock(SEXP resSignsSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type resSigns(resSignsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppCalcKDepthBlock(resSigns, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GSignTest_calcSimpDepth", (DL_FUNC) &_GSignTest_calcSimpDepth, 2},
    {"_GSignTest_signC", (DL_FUNC) &_GSignTest_signC, 1},
    {"_GSignTest_calc", (DL_FUNC) &_GSignTest_calc, 4},
    {"_GSignTest_calcDepth_def", (DL_FUNC) &_GSignTest_calcDepth_def, 2},
    {"_GSignTest_RcppCalcKDepthBlock", (DL_FUNC) &_GSignTest_RcppCalcKDepthBlock, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_GSignTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
