# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Simplified K-sign depth
#'
#' @description
#' \code{calcSimpDepth} calculates the simplified K-sign depth of a given vector of residuals.
#'
#' @param res [\code{numeric}]\cr
#'   numeric vector of residuals
#' @param K [\code{integer(1)}]\cr
#'   the parameter K of the simplified K-sign depth
#' @return [\code{numeric(1)}] the calculated simplified K-sign depth of res.
#'
#' @examples calcSimpDepth(rnorm(10), 3)
#' @export
calcSimpDepth <- function(res, K) {
    .Call(`_GSignTest_calcSimpDepth`, res, K)
}

signC <- function(x) {
    .Call(`_GSignTest_signC`, x)
}

calc <- function(x, k, ind, signOld) {
    .Call(`_GSignTest_calc`, x, k, ind, signOld)
}

calcDepth_def <- function(res, k) {
    .Call(`_GSignTest_calcDepth_def`, res, k)
}

RcppCalcKDepthBlock <- function(resSigns, K) {
    .Call(`_GSignTest_RcppCalcKDepthBlock`, resSigns, K)
}

prod_one_factor <- function(residuals, K, L) {
    .Call(`_GSignTest_prod_one_factor`, residuals, K, L)
}

asymp_K_depth <- function(residuals, K) {
    .Call(`_GSignTest_asymp_K_depth`, residuals, K)
}

