# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title k Sign Depth
#'
#' @description
#' \code{calcDepth} calculates the k Sign Depth of a given vector of residuals.
#'
#' @param res [\code{numeric}]\cr
#'   numeric vector of residuals
#' @param k [\code{integer(1)}]\cr
#'   the k of the depth-formula
#' @return [\code{numeric(1)}] the calculated k-Depth of res.
#'
#' @examples calcDepth(rnorm(10), 3)
#' @export
calcDepth <- function(res, k) {
    .Call(`_RobRegTest_calcDepth`, res, k)
}

#' @title Simplified k Sign Depth
#'
#' @description
#' \code{calcSimpDepth} calculates the simplified k Sign Depth of a given vector of residuals.
#'
#' @param res [\code{numeric}]\cr
#'   numeric vector of residuals
#' @param k [\code{integer(1)}]\cr
#'   the k of the depth-formula
#' @return [\code{numeric(1)}] the calculated simplified k-Depth of res.
#'
#' @examples calcSimpDepth(rnorm(10), 3)
#' @export
calcSimpDepth <- function(res, k) {
    .Call(`_RobRegTest_calcSimpDepth`, res, k)
}

